# 跑图检测配置
detection:
  # 检测时间窗口（秒）- 在此时间内统计生成的区块数量
  time-window: 30
  
  # 是否启用高度过滤
  height-filter-enabled: false
  
  # 高度过滤阈值（当玩家y坐标大于此值时忽略检测）
  height-threshold: 200
  
  # 间歇检测时间（秒）- 触发检测后等待多久再次检测
  cooldown-seconds: 3
  
  # 连续检测次数阈值（达到此次数后封禁玩家）
  continuous-threshold: 5
  
  # 玩家在水中时是否禁用检测（默认true，类似鞘翅不飞行时的处理）
  disable-detection-in-water: true
  
  # 维度切换后的冷却时间（秒）- 切换到主世界/末地/地狱后多久内不进行检测通知和封禁
  dimension-switch-cooldown-seconds: 30

# 封禁配置
ban:
  # 封禁时长（分钟）
  duration-minutes: 10

# 消息配置
messages:
  # 控制台消息
  console:
    detection: "[Anti-paotu] 已检测到玩家%player%触发跑图阈值，在%time%秒内生成了%chunks%个区块，连续次数%count%"
    ban: "[Anti-paotu] 已将连续多次触发跑图阈值的玩家%player%封禁"
  
  # 管理员消息（拥有antipaotu.notice权限的玩家）
  admin:
    detection: "§e[Anti-paotu] §f已检测到玩家 §c%player% §f触发跑图阈值，在 §6%time% §f秒内生成了 §6%chunks% §f个区块，连续次数 §c%count%"
    ban: "§e[Anti-paotu] §f已将连续多次触发跑图阈值的玩家 §c%player% §4封禁"
  
  # 玩家消息
  player:
    warning: "§c已触发跑图阈值，如果你连续触发此阈值会导致你被临时封禁！"
    ban-kick: "§c你因连续触发多次跑图检测，被暂时禁止进入服务器\n§e请在%time%分钟后再试"
    ban-login: "§c你因连续触发多次跑图检测，被暂时禁止进入服务器\n§e请在%time%分钟后再试"
  
  # 命令回复消息
  commands:
    reload-success: "§a配置文件重载成功！"
    reload-failed: "§c配置文件重载失败: %error%"
    player-not-found: "§c玩家 %player% 未找到！"
    player-not-online: "§c玩家 %player% 不在线！"
    no-detection-data: "§e玩家 %player% 没有检测数据"
    status-info: "§a玩家 %player% 状态:\n§7- 连续检测次数: %count%\n§7- 上次检测时间: %time%\n§7- 是否被封禁: %banned%"
    unban-success: "§a已解除玩家 %player% 的封禁"
    not-banned: "§e玩家 %player% 没有被封禁"
    no-permission: "§c你没有权限使用此命令！"
    usage-main: "§e使用方法: /antipaotu <reload|status|unban>"
    usage-status: "§e使用方法: /antipaotu status <玩家名>"
    usage-unban: "§e使用方法: /antipaotu unban <玩家名>"

# 调试配置
debug:
  # 是否启用调试模式
  enabled: false
  
  # 是否在控制台输出详细信息
  verbose: false

# OneBot QQ机器人配置
onebot:
  # 是否启用OneBot功能
  enabled: false
  
  # OneBot WebSocket地址
  websocket-url: ""
  
  # OneBot访问令牌（可选）
  access-token: ""
  
  # 要发送消息的QQ群号列表
  group-ids: 
    - 0
    # - 123456789
    # - 987654321
  
  # 要发送消息的QQ号列表
  private-ids:
    - 0
    # - 1234567890
    # - 0987654321
  
  # 连接超时时间（秒）
  connect-timeout: 10
  
  # QQ消息模板
  messages:
    detection: "已检测到玩家%player%触发跑图阈值，在%time%秒内生成了%chunks%个区块，连续次数%count%"
    ban: "由于多次触发跑图阈值，玩家%player%被暂时禁止进入服务器" 