name: Anti-Paotu
version: '1.1'
main: com.whitelu.antipaotu.AntiPaotuPlugin
author: whitelu
description: When a player's running map is detected, send a notification
api-version: '1.21'
folia-supported: true

commands:
  antipaotu:
    description: '反跑图插件管理命令'
    usage: '使用方法: /antipaotu <reload|status|unban> [参数]'
    permission: antipaotu.admin
    aliases: [ap]

permissions:
  antipaotu.admin:
    description: '管理反跑图插件的权限'
    default: op
  antipaotu.notice:
    description: '接收跑图检测通知的权限'
    default: op
  antipaotu.bypass:
    description: '跳过跑图检测的权限'
    default: false
  antipaotu.reload:
    description: '重载配置文件的权限'
    default: op
  antipaotu.status:
    description: '查看玩家状态的权限'
    default: op
  antipaotu.unban:
    description: '解除玩家封禁的权限'
    default: op 